//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Documentrevision))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Userdocument))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Folder))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.User))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Documentrevision))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Userdocument))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Folder))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.User))]
    public partial class EntityObject : Client.WcfServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documentrevision", Namespace="http://schemas.datacontract.org/2004/07/Server", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Documentrevision : Client.WcfServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Document DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS DocumentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS UserReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int documentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int editorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Document Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS DocumentReference {
            get {
                return this.DocumentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentReferenceField, value) != true)) {
                    this.DocumentReferenceField = value;
                    this.RaisePropertyChanged("DocumentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creationTime {
            get {
                return this.creationTimeField;
            }
            set {
                if ((this.creationTimeField.Equals(value) != true)) {
                    this.creationTimeField = value;
                    this.RaisePropertyChanged("creationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int documentId {
            get {
                return this.documentIdField;
            }
            set {
                if ((this.documentIdField.Equals(value) != true)) {
                    this.documentIdField = value;
                    this.RaisePropertyChanged("documentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int editorId {
            get {
                return this.editorIdField;
            }
            set {
                if ((this.editorIdField.Equals(value) != true)) {
                    this.editorIdField = value;
                    this.RaisePropertyChanged("editorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Server", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Document : Client.WcfServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Documentrevision[] DocumentrevisionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS UserReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Userdocument[] UserdocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int creatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Documentrevision[] Documentrevisions {
            get {
                return this.DocumentrevisionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentrevisionsField, value) != true)) {
                    this.DocumentrevisionsField = value;
                    this.RaisePropertyChanged("Documentrevisions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Userdocument[] Userdocuments {
            get {
                return this.UserdocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserdocumentsField, value) != true)) {
                    this.UserdocumentsField = value;
                    this.RaisePropertyChanged("Userdocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creationTime {
            get {
                return this.creationTimeField;
            }
            set {
                if ((this.creationTimeField.Equals(value) != true)) {
                    this.creationTimeField = value;
                    this.RaisePropertyChanged("creationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creatorId {
            get {
                return this.creatorIdField;
            }
            set {
                if ((this.creatorIdField.Equals(value) != true)) {
                    this.creatorIdField = value;
                    this.RaisePropertyChanged("creatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Userdocument", Namespace="http://schemas.datacontract.org/2004/07/Server", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Userdocument : Client.WcfServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Document DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS DocumentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Folder FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS FolderReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS UserReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int documentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int folderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Document Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS DocumentReference {
            get {
                return this.DocumentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentReferenceField, value) != true)) {
                    this.DocumentReferenceField = value;
                    this.RaisePropertyChanged("DocumentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Folder Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS FolderReference {
            get {
                return this.FolderReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderReferenceField, value) != true)) {
                    this.FolderReferenceField = value;
                    this.RaisePropertyChanged("FolderReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int documentId {
            get {
                return this.documentIdField;
            }
            set {
                if ((this.documentIdField.Equals(value) != true)) {
                    this.documentIdField = value;
                    this.RaisePropertyChanged("documentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int folderId {
            get {
                return this.folderIdField;
            }
            set {
                if ((this.folderIdField.Equals(value) != true)) {
                    this.folderIdField = value;
                    this.RaisePropertyChanged("folderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folder", Namespace="http://schemas.datacontract.org/2004/07/Server", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Folder : Client.WcfServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Folder[] Folder1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Folder Folder2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS Folder2ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Userdocument[] UserdocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.User[] UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> parentFolderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Folder[] Folder1 {
            get {
                return this.Folder1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Folder1Field, value) != true)) {
                    this.Folder1Field = value;
                    this.RaisePropertyChanged("Folder1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Folder Folder2 {
            get {
                return this.Folder2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Folder2Field, value) != true)) {
                    this.Folder2Field = value;
                    this.RaisePropertyChanged("Folder2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS Folder2Reference {
            get {
                return this.Folder2ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Folder2ReferenceField, value) != true)) {
                    this.Folder2ReferenceField = value;
                    this.RaisePropertyChanged("Folder2Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Userdocument[] Userdocuments {
            get {
                return this.UserdocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserdocumentsField, value) != true)) {
                    this.UserdocumentsField = value;
                    this.RaisePropertyChanged("Userdocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> parentFolderId {
            get {
                return this.parentFolderIdField;
            }
            set {
                if ((this.parentFolderIdField.Equals(value) != true)) {
                    this.parentFolderIdField = value;
                    this.RaisePropertyChanged("parentFolderId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Server", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : Client.WcfServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Documentrevision[] DocumentrevisionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Document[] DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Folder FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS FolderReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.Userdocument[] UserdocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rootFolderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Documentrevision[] Documentrevisions {
            get {
                return this.DocumentrevisionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentrevisionsField, value) != true)) {
                    this.DocumentrevisionsField = value;
                    this.RaisePropertyChanged("Documentrevisions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Document[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Folder Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS FolderReference {
            get {
                return this.FolderReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderReferenceField, value) != true)) {
                    this.FolderReferenceField = value;
                    this.RaisePropertyChanged("FolderReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.Userdocument[] Userdocuments {
            get {
                return this.UserdocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserdocumentsField, value) != true)) {
                    this.UserdocumentsField = value;
                    this.RaisePropertyChanged("Userdocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rootFolderId {
            get {
                return this.rootFolderIdField;
            }
            set {
                if ((this.rootFolderIdField.Equals(value) != true)) {
                    this.rootFolderIdField = value;
                    this.RaisePropertyChanged("rootFolderId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfFolderrvh1PiYS", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfFolderrvh1PiYS : Client.WcfServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Documentrevision[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Documentrevision))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Userdocument[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Userdocument))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Folder))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Folder[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.User[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.Document[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfUserrvh1PiYS", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfUserrvh1PiYS : Client.WcfServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS))]
    public partial class EntityReference : Client.WcfServiceReference.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.WcfServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.WcfServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfDocumentrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfFolderrvh1PiYS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.WcfServiceReference.EntityReferenceOfUserrvh1PiYS))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfDocumentrvh1PiYS", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfDocumentrvh1PiYS : Client.WcfServiceReference.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUser", ReplyAction="http://tempuri.org/IService/AddUserResponse")]
        bool AddUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        void AddFolder(string name, int parentFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddDocument", ReplyAction="http://tempuri.org/IService/AddDocumentResponse")]
        void AddDocument(string name, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByEmailAndPass", ReplyAction="http://tempuri.org/IService/GetUserByEmailAndPassResponse")]
        int GetUserByEmailAndPass(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        Client.WcfServiceReference.User GetUserById(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByEmail", ReplyAction="http://tempuri.org/IService/GetUserByEmailResponse")]
        Client.WcfServiceReference.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDocumentById", ReplyAction="http://tempuri.org/IService/GetDocumentByIdResponse")]
        Client.WcfServiceReference.Document GetDocumentById(int documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDocumentByName", ReplyAction="http://tempuri.org/IService/GetDocumentByNameResponse")]
        Client.WcfServiceReference.Document GetDocumentByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFolder", ReplyAction="http://tempuri.org/IService/GetFolderResponse")]
        Client.WcfServiceReference.Folder GetFolder(int folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteFolder", ReplyAction="http://tempuri.org/IService/DeleteFolderResponse")]
        void DeleteFolder(int folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDocumentReference", ReplyAction="http://tempuri.org/IService/DeleteDocumentReferenceResponse")]
        void DeleteDocumentReference(int userId, int documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDocument", ReplyAction="http://tempuri.org/IService/DeleteDocumentResponse")]
        void DeleteDocument(int documentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.WcfServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.WcfServiceReference.IService>, Client.WcfServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddUser(string email, string password) {
            return base.Channel.AddUser(email, password);
        }
        
        public void AddFolder(string name, int parentFolderId) {
            base.Channel.AddFolder(name, parentFolderId);
        }
        
        public void AddDocument(string name, int userId) {
            base.Channel.AddDocument(name, userId);
        }
        
        public int GetUserByEmailAndPass(string email, string pass) {
            return base.Channel.GetUserByEmailAndPass(email, pass);
        }
        
        public Client.WcfServiceReference.User GetUserById(int userId) {
            return base.Channel.GetUserById(userId);
        }
        
        public Client.WcfServiceReference.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public Client.WcfServiceReference.Document GetDocumentById(int documentId) {
            return base.Channel.GetDocumentById(documentId);
        }
        
        public Client.WcfServiceReference.Document GetDocumentByName(string name) {
            return base.Channel.GetDocumentByName(name);
        }
        
        public Client.WcfServiceReference.Folder GetFolder(int folderId) {
            return base.Channel.GetFolder(folderId);
        }
        
        public void DeleteFolder(int folderId) {
            base.Channel.DeleteFolder(folderId);
        }
        
        public void DeleteDocumentReference(int userId, int documentId) {
            base.Channel.DeleteDocumentReference(userId, documentId);
        }
        
        public void DeleteDocument(int documentId) {
            base.Channel.DeleteDocument(documentId);
        }
    }
}
